services:
    app:
        container_name: ${PROJECT_NAME}_nuxt_dev
        ports:
            - "3000:3000"
            - "24678:24678"
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./mount/apps/nuxt/:/srv
        working_dir: /srv
        command: >
            sh -c "
            chown -R node:node /srv &&
            npx nuxi dev --dotenv .env.local
            "

    mysql:
        container_name: ${PROJECT_NAME}_mysql_dev
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${PROJECT_NAME}_dev
            MYSQL_USER: ${PROJECT_NAME}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql:rw

    phpmyadmin:
        container_name: ${PROJECT_NAME}_pma_dev
        image: phpmyadmin
        environment:
            DOMAIN_NAME: pma.${PROJECT_NAME}.dev
            PMA_HOSTS: mysql
            PMA_USER: root
            PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            PMA_ARBITRARY: 1

    caddy:
        container_name: ${PROJECT_NAME}_caddy_dev
        image: caddy:2.8
        environment:
            DOMAIN_NAME: ${PROJECT_NAME}.dev
            PROJECT_NAME: ${PROJECT_NAME}
        volumes:
            - ./caddy/Caddyfile:/etc/caddy/Caddyfile
            - ./caddy/${DOMAIN_NAME}.pem:/usr/local/etc/caddy/certs/${DOMAIN_NAME}.pem
            - ./caddy/${DOMAIN_NAME}-key.pem:/usr/local/etc/caddy/certs/${DOMAIN_NAME}-key.pem
            - ./mount/apps/nuxt/:/srv

volumes:
    mysql_data: