name: Lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Lint
        run: 
          npm install 
          npm run lint
          npm run type-check
