name: Lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/nuxt
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Get Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: ./apps/nuxt/pnpm-lock.yaml

      - name: Lint
        run:
          pnpm install &&
          pnpm run lint &&
          npx nuxi typecheck
